### ISSUE TITLE
Estudar DNS

### ISSUE THREAD

**Issue by boidacarapreta** [Aplantica-Horta-Digital/Aplantica-Horta-Digital.github.io#10]
Assistir aos vídeos do NIC.br, conforme [documento de EaD do Slack](https://ortadigital.slack.com/files/TUN198PJ9/F010CF3GR4M) (acesso restrito ao time).

**Comment by boidacarapreta** [comment]
A importância do DNS nas redes: https://www.youtube.com/watch?v=epWv0-eqRMw

**Comment by boidacarapreta** [comment]
Como funciona a Internet: https://www.youtube.com/playlist?list=PLQq8-9yVHyOYMFAc9v7Yb_cqmNMksEdrk

**Comment by boidacarapreta** [comment]
A pedido, documentação em texto (a ler preferencialmente nesta sequência):
1. [What is DNS? How DNS works](https://www.cloudflare.com/learning/dns/what-is-dns/)?, da Cloudfare.
1. [An Introduction to DNS Terminology, Components, and Concepts](https://www.digitalocean.com/community/tutorials/an-introduction-to-dns-terminology-components-and-concepts), da Digital Ocean.
1. O verbete sobre [DNS em inglês](https://en.wikipedia.org/wiki/Domain_Name_System) da Wikipédia.

Como será usado AWS no projeto, já é interessante olhar o [serviço Route53](https://aws.amazon.com/pt/route53/).

**Comment by boidacarapreta** [comment]
Questionário de retorno [publicado no Google Classroom](https://classroom.google.com/w/NTYxNzMwODE2NDha/tc/NTYxNTk2MTA4MTFa) (acesso restrito).

**Comment by mtusantana** [comment]
O sistema DNS seria semelhante a uma lista telefônica da internet, onde um site possui uma sequência de códigos para mostrar onde encontrar dentre todos servidores. Cada dispositivo conectado a internet possui um endereço de IP exclusivo que outras maquias utilizam para encontrar esse dispositivo. Os servidores DNS fazem com que o usuário não precise que memorizem esses endereços IP (que seria muito difícil memorizar vários), permitindo que memorize os “links”, sendo nomes mais amigáveis para memorizar. 

Os domínios utilizam alguns termos importantes, sendo alguns deles: 

**DNS:** Sistema de nome de domínio  

**Nome de domínio:** Seria o nome “Amigável” de memorizar. Ex: "google.com" 

**Endereço IP:** Seria um ponto endereçável na rede. Cada equipamento ou ponto da rede possui um IP diferente. Ex: 192.168.1.201 

**Domínio de nível (TLD):** É a parte mais geral de um domínio. Eles estão no topo da hierarquia em termos de nomes de domínio. Ex: "com", "net", "org", "gov", "edu" e "io". 

**Anfitriões:** Dentro de um domínio, o proprietário do domínio pode definir hosts individuais, que se referem a computadores ou serviços separados acessíveis por um domínio. Exemplo, em modo geral, um servidor Web pode ter o domínio (exemplo.com) e tambem atravez de um host “www” ( www.example.com ). Ou acesso à APE com o host "api" (api.example.com). ou pode ter acesso ftp definindo um host chamado "ftp" ou "arquivos" (ftp.example.com ou files.example.com).
