### ISSUE TITLE
Compra curso na Udemy.

### ISSUE THREAD

**Issue by Brendacs2020** [Aplantica-Horta-Digital/Aplantica-Horta-Digital.github.io#15]
(Solicitação da equipe de software)

**Comment by Brendacs2020** [comment]
Segue links dos cursos comprados:
https://www.udemy.com/course/rest-apis-com-python-e-flask/
https://www.udemy.com/course/curso-reactjs/

Usuario:  projetoaplantica@gmail.com
Senha:aplantica2020

**Comment by charcoast** [comment]
Cursos adquiridos. Alunos já tem acesso.
