### ISSUE TITLE
Organização das equipes

### ISSUE THREAD

**Issue by pedrofagundes10** [Aplantica-Horta-Digital/Aplantica-Horta-Digital.github.io#7]

**Comment by pedrofagundes10** [comment]
# Criação da hierarquia das equipes.
1. Hardware:
-Líder: Guilherme
-Sub líder:???
-Analista de desenvolvimento:???

1. Software:
-Líder: Vinicius
-Sub líder:???
-Analista de desenvolvimento:???

1. Marketing
-Líder: Manuela
-Sub líder:???
-Analista de desenvolvimento:???
1. RH

-Líder: Brenda
-Sub líder:???
-Analista de desenvolvimento:

**Comment by Brendacs2020** [comment]
> # Criação da hierarquia das equipes.
> 1. Hardware: 
>    -Líder: Guilherme -Sub 
>    líder: ??? 
>    -Analista de desenvolvimento: ???
> 2. Software: 
>    -Líder: Vinicius -Sub 
>    líder: Bruno 
>    -Analista de desenvolvimento: Bruna / Bruno
> 3. Marketing 
>    -Líder: Manuela -Sub 
>    líder: Isabella 
>    -Analista de desenvolvimento: Lilia
> 4. RH
>    -Líder: Brenda -Sub
>    -líder: Fernanda
>

**Comment by charcoast** [comment]
1. Hardware:
-Líder: Guilherme 
-Sub líder: João Pedro Lange

2. Software:
-Líder: Vinicius 
-Sub líder: Bruno
-Analista de desenvolvimento: Bruna / Bruno

3. Marketing
-Líder: Manuela 
-Sub líder: Isabella
-Analista de desenvolvimento: Lilia

4. RH
-Líder: Brenda 
-Sub líder: Fernanda

**Comment by charcoast** [comment]
1. Hardware:
-Líder: Guilherme 
-Sub líder: Enzo
2. Software:
-Líder: Vinicius 
-Sub líder: Bruno
-Analista de desenvolvimento: Bruna / Bruno

3. Marketing
-Líder: Manuela 
-Sub líder: Isabella
-Analista de desenvolvimento: Lilia

4. RH
-Líder: Brenda 
-Sub líder: Fernanda
